version: "2"
services:
  mongodb:
    image: mongo:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - redis
  web:
    image: web:v1
    container_name: web
    depends_on:
    - catalogue
    - cart
    ports:
    - "80:80"
  redis:
    image: redis
    container_name: redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
  mysql:
    image: mysql:v1
    container_name: mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql
networks:
  roboshop:
    driver: bridge