version: "2"
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - redis
  web:
    image: web:v1
    container_name: web
    depends_on:
    - catalogue
    - cart
    ports:
    - "80:80"
  redis:
    image: redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
networks:
  roboshop:
    driver: bridge