version: "2"
services:
  mongodb:
    image: mongo:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: catalogue:v2
    container_name: catalogue
    depends_on:
    - redis
    - mongodb
  web:
    image: web:v1
    container_name: web
    depends_on:
    - catalogue
    - cart
    ports:
    - "80:80"
  redis:
    image: redis
    container_name: redis
    volumes:
    - redis:/data
  cart:
    image: cart:v2
    container_name: cart
    depends_on:
    - catalogue
    - redis
  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: shipping:v2
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  ratings:
    image: ratings:v1
    container_name: ratings
    depends_on:
    - mysql
  dispatch:
    image: dispatch:v1
    container_name: dispatch
    depends_on:
    - rabbitmq
networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/mongodb'
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/mysql'
  redis:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/redis'
  rabbitmq:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/rabbitmq'